### ISSUE TITLE
"too few arguments" with sexagesimal input

### ISSUE THREAD

**Issue by dancoe** [mattjhill/find_tgt_info#1]
Excellent tool, Matt!  Very easy to use and it works well for decimal RA and Dec.  But when I try sexagesimal, I receive the errors below.  The first appears to be just a matter of adding "import string".  The second is a little trickier: the minus sign makes the Dec look like an input argument.  Thank you!

python find_tgt_info.py 00:00:00 00:00:00
Using Equatorial Coordinates
Traceback (most recent call last):
  File "find_tgt_info.py", line 425, in <module>
    main(args)
  File "find_tgt_info.py", line 116, in main
    ra  = convert_ddmmss_to_float(args.ra) * 15. * D2R
  File "find_tgt_info.py", line 27, in convert_ddmmss_to_float
    aline = string.split(astring,':')

python find_tgt_info.py 00:00:00 -10:00:00
usage: find_tgt_info.py [-h] [--pa PA] [--save_plot SAVE_PLOT]
                        [--save_table SAVE_TABLE] [--instrument INSTRUMENT]
                        ra dec
find_tgt_info.py: error: too few arguments

**Comment by mattjhill** [comment]
Thanks for testing!  

I've fixed the string issue but as you said the argument parsing issue is a little trickier.  You can work around this by adding a `--` before the Dec when it has a negative sign and making sure optional arguments are specified before the coordinates e.g.

`python find_tgt_info.py --instrument nircam 00:00:00 -- -10:00:00`

I'm not completely satisfied with that solution, but I've added a note to the README explaining the bug and work-around. I'll have to do some thinking to figure out if there is a better solution.

**Comment by dancoe** [comment]
Great, thank you, Matt!  And fixing that bug sometime would be great.  I can imagine a hack where you loop through the sys.argv (separately from the parser) checking for any element beginning with '-' followed by a digit.  If it finds one, it will always be Dec.

**Comment by mattjhill** [comment]
Okay, should be fixed now.
